---

language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
before_install:
 - sudo add-apt-repository -y ppa:chrysn/openscad
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq inkscape openscad
script:
  - python make_machine.py dibond
  - python make_machine.py sturdy
